# Generated by Django 3.2.12 on 2022-03-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzed_Data',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('y_price', models.IntegerField()),
                ('y_difference', models.IntegerField()),
                ('w_price', models.IntegerField()),
                ('w_differnece', models.IntegerField()),
                ('oneday_tradevolume', models.IntegerField()),
                ('y_tradevolume', models.IntegerField()),
                ('w_tradevolume', models.IntegerField()),
                ('nt_highest', models.IntegerField()),
                ('nt_lowest', models.IntegerField()),
                ('nt_percentage', models.DecimalField(decimal_places=3, max_digits=3)),
                ('tt_highest', models.IntegerField()),
                ('tt_lowest', models.IntegerField()),
                ('tt_percentage', models.DecimalField(decimal_places=3, max_digits=3)),
                ('sales_21', models.IntegerField()),
                ('operatingincome_21', models.IntegerField()),
                ('netincome_21', models.IntegerField()),
                ('sales_20', models.IntegerField()),
                ('operatingincome_20', models.IntegerField()),
                ('netincome_20', models.IntegerField()),
                ('market_cap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Corperations',
            fields=[
                ('c_name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tradePrice', models.IntegerField()),
            ],
        ),
    ]
