# Generated by Django 3.2.12 on 2022-03-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corperations',
            old_name='code',
            new_name='c_code',
        ),
        migrations.RenameField(
            model_name='corperations',
            old_name='tradePrice',
            new_name='c_price',
        ),
    ]
