# Generated by Django 3.2.12 on 2022-03-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0004_alter_corperations_market_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceinDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('tradePrice', models.IntegerField()),
                ('openingPrice', models.IntegerField()),
                ('highPrice', models.IntegerField()),
                ('lowPrice', models.IntegerField()),
            ],
        ),
    ]
