# Generated by Django 3.2.12 on 2022-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0005_priceindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='corperations',
            name='last_updated_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
