# Generated by Django 3.2.12 on 2022-03-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0006_corperations_last_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceindate',
            name='volume',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
