# Generated by Django 3.2.12 on 2022-03-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Analyze',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True)),
                ('price', models.IntegerField()),
                ('y_price', models.IntegerField()),
                ('y_difference', models.IntegerField()),
                ('w_price', models.IntegerField()),
                ('w_differnece', models.IntegerField()),
                ('oneday_tradevolume', models.IntegerField()),
                ('y_tradevolume', models.IntegerField()),
                ('w_tradevolume', models.IntegerField()),
                ('nt_highest', models.IntegerField()),
                ('nt_lowest', models.IntegerField()),
                ('nt_percentage', models.DecimalField(decimal_places=3, max_digits=3)),
                ('tt_highest', models.IntegerField()),
                ('tt_lowest', models.IntegerField()),
                ('tt_percentage', models.DecimalField(decimal_places=3, max_digits=3)),
                ('sales_21', models.IntegerField()),
                ('operatingincome_21', models.IntegerField()),
                ('netincome_21', models.IntegerField()),
                ('sales_20', models.IntegerField()),
                ('operatingincome_20', models.IntegerField()),
                ('netincome_20', models.IntegerField()),
                ('market_cap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('code', models.CharField(max_length=10)),
                ('date', models.DateField(primary_key=True)),
                ('tradePrice', models.IntegerField()),
                ('openingPrice', models.IntegerField()),
                ('candleAccTradeVolume', models.IntegerField()),
                ('changePrice', models.IntegerField()),
                ('changeRate', models.FloatField()),
            ],
        ),
    ]
